### ISSUE TITLE
Separar o CSS e JS do PHP

### ISSUE THREAD

**Issue by leobaiano** [mariovalney/switch-user#1]
É legal manter CSS e JS em arquivos próprios, assim o arquivo .php fica mais legível e melhor para manutenção.

**Comment by mariovalney** [comment]
Exato! Mas como estava fazendo apenas para teste, acabei deixando assim mesmo...
Até já tinha feito essa melhoria aqui na versão local, mas vou aceitar o PR, só adiciona o sufixo **su_** na função, por favor :D

**Comment by leobaiano** [comment]
Feito @mariovalney

**Comment by mariovalney** [comment]
Valeu :D
