### ISSUE TITLE
Bloquear o acesso direto ao arquivo e ao diretório do plugin

### ISSUE THREAD

**Issue by leobaiano** [mariovalney/switch-user#3]
É uma boa prática, no desenvolvimento de plugins para WordPress, bloquear o acesso direto ao arquivo do plugin e ao diretório.

Para bloquear o acesso ao diretório basta incluir um .php vazio;
Para bloquear o acesso direto ao arquivo do plugin é só verificar se a constante ABSPATH existe, ela é definida pelo WL, então se o acesso for direto ela não existirá e ai é só dar exit.

**Comment by mariovalney** [comment]
A ideia do plugin é ser de uso apenas em desenvolvimento, então acabei esquecendo desses dois detalhes. Valeu!
